# Bingo Config
grid-width: 5
season-id: 1

# Rewards based on unlock type
rewards:
  single: 100
  line: 250
  card: 5000

# Database setup
database:
  # What type of datastore to use, one of:
  # - mock: Runs an in-memory mock database, only useful for testing with no setup required
  # - primary: Uses the primary database on your Database plugin configuration
  # - secondary: Uses the primary database on your Database plugin configuration
  # Database plugin (https://github.com/OvercastCommunity/Database) is required for the later 2 options-
  type: mock
  # If using mock database, this is the configured bingo card. Ignored for primary and secondary.
  mock-data:
    - slug: 'alphabet-killer'
      name: 'Lexical Conquest'
      description: 'Strike down foes forming a linguistic chain.;It''s easy as 1 2 3;Kill them in A B C.'
      idx: 0
      hintLevel: 0
    - slug: 'anvil-killer'
      name: 'Heavy Metal'
      description: 'Crush your foe with gravity''s aid.'
      idx: 1
      hintLevel: 0

# Objective config options
anvil-smasher:
  falling-block-name: "ANVIL"
armour-sets-crafted:
  required-count: 9
arrow-collect:
  arrow-pickups: 384
arrow-total-distance:
  min-arrow-distance-count: 10000
big-fall:
  min-fall-height: 100
block-break:
  material-name: null
  block-data: -1
  block-break-count: 1000
cactus-hugger:
  cactus-height: 5
chat-message:
  required-text: "UwU"
  ignore-case: true
defender-kill:
  objective-max-range: 5
  objective-max-size: 40
eating:
  foods-required: 3
fall-damage-taken:
  min-fall-height: 20
  max-fall-health-remaining: 1
flower-pot:
  allow-any: false
food-eater:
  food-name: "GOLDEN_APPLE"
  min-count: 100
golden-apple-full:
  min-absorption-health: 4
hedgehog:
  min-arrows: 25
high-killer:
  kills-required: 100
icarus-height:
  min-vertical-velocity: 6 # About 100 blocks in the air
  delay-ticks: 2
item-whack:
  material-name: "STICK"
kill-assist-streak:
  min-assist-count: 5
kill-streak:
  required-streak: 10
match-length:
  required-mins: 60
kill-messages:
  min-death-message-types: 35
picky-voter:
  min-map-votes: 4
  max-map-votes: 4
player-craft:
  material-name: "PISTON_BASE"
player-shifting:
  radius: 4
  same-team-count: 1
  other-team-count: 2
quick-kills:
  kills-required: 3
  time-threshold-seconds: 5
ride-distance:
  riding-distance: 100
  allow-vertical: false
ride-time:
  riding-seconds: 30
  entity-type: "MINECART"
shared-monument:
  difficulty-multiplier: 0.7
  min-required-players: 3
water-dropper:
  min-fall-height: 100
support-capper:
  nearby-player-distance: 6
tnt-launcher:
  min-tnt-distance: 70
void-eating:
  max-height: 0
  food-name: "GOLDEN_APPLE"
wool-collector:
  min-wool-count: 5
yapper:
  min-kills: 5
  chars-per-kill: 100